trigger:
  branches:
    include:
      - development
      - master

jobs:

- job: BuildFixitMobileComponentLib

  pool:
    vmImage: 'windows-2019'
    displayName: 'Run Main Build and Test Pipeline'
    
  steps:

  # Install
  - task: Npm@1
    displayName: 'Install Dependencies'
    inputs:
      command: 'install'
  
  # Test
  - task: Npm@1
    displayName: 'Run Unit Tests'
    inputs:
      command: 'custom'
      customCommand: 'run test'

  # Publishes npm package
  - task: Npm@1
    displayName: 'Publish Artifact'
    inputs:
      command: 'publish'
      publishRegistry: 'useFeed'
      publishFeed: '08d378fd-be72-4c80-9ce4-1a7c754efb98/7ba6392b-6ff3-4d8f-bdc4-0a4bcdee1710'
  



